### ISSUE TITLE
Impossible to set the $font-size-default with percentage values.

### ISSUE THREAD

**Issue by gperriard** [liip/kanbasu#29]
In order to let the user choose his default font-size, I would like to be able to set the $font-size-default with percentage values.
WDYT?

**Comment by LeBenLeBen** [comment]
The historical reason to set body `font-size` in percentages was because of a bug in old versions of IE. Today I don’t see the point of doing it especially since setting a fix value allow us to do various useful calculations.

Is there any other reason that prevents you from using pixels?

**Comment by gperriard** [comment]
The reason is the user can adapt the default browser font-size in settings, on modern browsers.
- Firefox - https://support.mozilla.org/en-US/kb/font-size-and-zoom-increase-size-of-web-pages#w_how-to-only-change-the-size-of-the-text
- Chrome - https://support.google.com/chrome/answer/96810?hl=en
- Edge - http://windows.microsoft.com/en-us/windows-10/change-font-style-and-size-for-reading-view-in-microsoft-edge

When you set `font-size: 20px` on the `<html>` element you don't let the ability to the user to have his personal settings applied. Using percentage for `font-size` on the `<html>` element and rem unit for children make your layout scale when the user change his font settings.
http://kyleschaeffer.com/development/css-font-size-em-vs-px-vs-pt-vs/

This is definitely better in terms of accessibility.

You're point about the useful calculation is valid though we could do it a bit differently.

**Comment by LeBenLeBen** [comment]
Seems legit, I’ll see how I can make both live together then.
