### ISSUE TITLE
Replace `left` and `right` by `start` and `end`

### ISSUE THREAD

**Issue by Hywan** [liip/kanbasu#37]
Hello 😃,

This is cool to have `text-right`, `text-left` etc., but it does not adapt to the current text direction of the page. So having `text-start` and `text-end` that adapts to `:root[dir="…"]` would be awesome.

Thank ❤️.

**Comment by LeBenLeBen** [comment]
I think this would slightly complicate a very simple helper and could confuse most users. The use case seems pretty uncommon and could be easily done per project. I don’t think it would be beneficial for the majority to make it the default in Kanbasu.
