### ISSUE TITLE
Typo in Typography component

### ISSUE THREAD

**Issue by hsmio** [liip/kanbasu#49]
Small typo in http://kanbasu.liip.ch/2/components/detail/typography.html, notes are rendered in the component instead of being in the "notes" tab:

```
--- notes: | Use these only when dedicated tags, such as `em` or `strong`, are not applicable. Since version 1.5.0, you can also restrict alignment to specific breakpoints by prefixing them with the media query name, for example `.lg-text-right` to match only large screens. Those breakpoints are mobile-first and therefor apply to the targeted breakpoint and above. ---
```

PS: great job @LeBenLeBen , I like the level of simplicity and clarity!

**Comment by LeBenLeBen** [comment]
Thanks for the report, now fixed on branch 2.0.0, will land with the next update.
