### ISSUE TITLE
Cannot use non-px unit for $font-size-default

### ISSUE THREAD

**Issue by sephii** [liip/kanbasu#52]
If you try to set `$font-size-default` to any unit other than `px`, you'll get the following error:

```
Error: node_modules/kanbasu/src/assets/scss/defaults/_forms.scss
Error: Incompatible units: 'px' and 'em'.
        on line 104 of node_modules/kanbasu/src/assets/scss/defaults/_forms.scss
>>   height: floor($field-calc-font-size*$field-line-height + $padding-vertical +
   ----------------^
```

This happens on Kanbasu 1.7.0.

**Comment by LeBenLeBen** [comment]
Yes, this is on purpose as specified in the [settings documentation](http://kanbasu.liip.ch/settings.html). It is required for calculating various other sizes.

However, the final value in the CSS is in percent, as recommended to allow cross-browser custom text size settings to work properly. See #29
