### ISSUE TITLE
Replace `parallelshell` by `npm-run-all`

### ISSUE THREAD

**Issue by bpeab** [liip/kanbasu#64]
We are starting to see some issues with `parallelshell` because of it's compatibility with newer node versions. In addition, `parallelshell` is in maintenance mode which means we're likely not to see fixes for the upcoming issues regarding node updates.

To resolve this issue, which already appeared for me, we should definitely switch to a solution like `npm-run-all` which offers the same features as `parallelshell`.

**Comment by bpeab** [comment]
See PR #65.

**Comment by LeBenLeBen** [comment]
Fixed by #65
